version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules   # Prevent host from overwriting node_modules
    working_dir: /app
    command: ["npm", "run", "dev"]
    networks:
      - app-network
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["python3", '-m', 'flask', 'run', '--debug']
    environment:
      - FLASK_APP=app.py
    networks:
      - app-network
networks:
  app-network:
    driver: bridge